apiVersion: v1
kind: Pod
metadata:
  name: test-webserver
spec:
  containers:
  - name: test-webserver
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/www/html
      name: mydir
  volumes:
  - name: mydir
    hostPath:
      path: /tmp/test
      type: DirectoryOrCreate
  