apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["sleep", "infinity"]
      env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: string-value
        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: number-value
      volumeMounts:
        - name: my-configmap
          mountPath: /config
  volumes:
    - name: my-configmap
      configMap:
        name: my-configmap
        items:
          - key: number-value
            path: number-value
          - key: string-value
            path: string-value
