pipeline {
    agent any
    environment {
        JWT_SECRET = credentials('jwt-secret')
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_REGION= credentials('aws-region')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'openlab', url: 'https://github.com/devops-new-world/openlabfree/openlab.git'
                dir('openlabfree/openlab') {
                    sh 'pwd' 
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('openlabfree/openlab') {
                    dir('backend') {
                        sh 'npm install'
                    }
                    dir('executor') {
                        sh 'pip install --no-cache-dir -r requirements.txt'
                    }
                }
            }
        }
        stage('Test Backend') {
            steps {
                dir('openlabfree/openlab/backend') {
                    sh 'npm test || true' 
                }
            }
        }
        stage('Test Executor') {
            steps {
                dir('openlabfree/openlab/executor') {
                    sh 'pytest || true' 
                }
            }
        }
        stage('Test Fetcher') {
            steps {
                dir('openlabfree/openlab/fetcher') {
                    sh 'go test ./... || true'  
                }
            }
        }

        stage('Build') {
            steps {
                dir('openlabfree/openlab') {
                    sh 'docker-compose build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('openlabfree/openlab') {
                    echo 'Running tests (add test scripts here)'
                    sh 'npm test || true'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('openlabfree/openlab') {
                    sh '''
                        export MONGODB_URI="${MONGODB_URI}"
                        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
                        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
                        export AWS_REGION="${AWS_REGION}"
                        docker-compose up -d
                    '''
                }
                sh '''
                    sudo nginx -t
                    sudo systemctl reload nginx
                '''
            }
        }
    }
    post {
        always {
            echo 'cleaning workspace'
            cleanWs()
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}