AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance in the public subnet with dynamic VPC and subnet imports
Parameters:
  VpcId:
    Type: String
    Description: The VPC ID where the EC2 instance will be deployed.
  PublicSubnetId:
    Type: String
    Description: The Public Subnet ID where the EC2 instance will be deployed.
  KeyPairName:
    Type: String
    Description: Name of the EC2 key pair to use.
  UserDataFileName:
    Type: String
    Description: The name of the user-data script file in the S3 bucket.
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket where the user-data script is stored.


Resources:
  # Security Group for EC2 Instance
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !Ref VpcId 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # EC2 Instance in the public subnet
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      ImageId: ami-04b4f1a9cf54c11d0  # Update this with the correct AMI for your region
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          aws s3 cp s3://${S3BucketName}/${UserDataFileName} /tmp/user-data.sh
          bash /tmp/user-data.sh
      Tags:
        - Key: Name
          Value: php-3-tier-webserver

Outputs:
  EC2PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
