AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 Key Pair for use in other stacks.

Parameters:
  KeyPairName:
    Description: Name of the EC2 Key Pair
    Type: String
    Default: my-key-pair

Resources:
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyPairName

Outputs:
  KeyPairNameOutput:
    Description: Name of the created EC2 Key Pair
    Value: !Ref EC2KeyPair
    Export:
      Name: KeyPairName
