AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketName:
    Description: The name of the S3 bucket where the user-data script is stored
    Type: String

  UserDataFileName:
    Description: The name of the user-data file in the S3 bucket
    Type: String
  KeyPairName:
    Description: Name of the EC2 key pair
    Type: String
    Default: my-key-pair
Resources:
  KeyPairStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/keypair.yaml"
      Parameters:
        KeyPairName: !Ref KeyPairName
        
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/vpc.yaml"
  BackendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - KeyPairStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/ec2-instance.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VPCID
        PublicSubnetId: !GetAtt NetworkStack.Outputs.PublicSubnet1ID
        KeyPairName: !GetAtt KeyPairStack.Outputs.KeyPairNameOutput  
        S3BucketName: !Ref S3BucketName
        UserDataFileName: !Ref UserDataFileName     
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/rds.yaml"
      Parameters:
        StackName: !Ref StackName  # Pass the StackName parameter to RDS
      #   VpcId: !GetAtt NetworkStack.Outputs.VPCID
      #   DBSubnetIds: !GetAtt NetworkStack.Outputs.DBSubnetIds
  # FrontendStorageStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/s3-template.yaml"
Outputs:
  VPCStackOutput:
    Description: The VPC stack output
    Value: !GetAtt NetworkStack.Outputs.VPCID

  # S3StackOutput:
  #   Description: The S3 stack output
  #   Value: !GetAtt FrontendStorageStack.Outputs.BucketName

  # RDSStackOutput:
  #   Description: The RDS stack output
  #   Value: !GetAtt DatabaseStack.Outputs.DBInstance

  EC2InstanceStackOutput:
    Description: The EC2 Instance stack output
    Value: !GetAtt BackendStack.Outputs.EC2PublicIP

  # RDSDatabaseEndpoint:
  #   Description: The RDS database endpoint
  #   Value: !GetAtt DatabaseStack.Outputs.SampleCloudFormationRDSInstanceEndPoint