AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/vpc-template.yaml"

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/rds-template.yaml"
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/ec2-instance.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VPCId
        PublicSubnetId: !GetAtt NetworkStack.Outputs.PublicSubnetId        
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/rds.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VPCId
        DBSubnetIds: !GetAtt NetworkStack.Outputs.DBSubnetIds
  FrontendStorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/my-cloudformation-templates-devops430/s3-template.yaml"
Outputs:
  VPCStackOutput:
    Description: The VPC stack output
    Value: !GetAtt VPCStack.Outputs.VPCID

  S3StackOutput:
    Description: The S3 stack output
    Value: !GetAtt S3Stack.Outputs.BucketName

  RDSStackOutput:
    Description: The RDS stack output
    Value: !GetAtt RDSStack.Outputs.DBInstance

  Php3TierStackOutput:
    Description: The PHP 3-tier stack output
    Value: !GetAtt Php3TierStack.Outputs.WebServer

  EC2InstanceStackOutput:
    Description: The EC2 Instance stack output
    Value: !GetAtt EC2InstanceStack.Outputs.EC2PublicIP