AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 Bucket for user-data script.

Parameters:
  S3BucketName:
    Description: Name of the S3 bucket for user-data script
    Type: String
    Default: my-userdata-bucket

Resources:
  # S3 Bucket for user-data script
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # (Optional) S3 Bucket Policy - Public Read Access for User-Data Script
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3BucketName

  S3BucketURL:
    Description: S3 bucket URL
    Value: !Sub "https://s3.amazonaws.com/${S3BucketName}/"
