- name: Create user
  hosts: all
  become: yes
  vars:
    user: "abcxyz"
    password: "{{ 'abcxyz' | password_hash('sha512') }}"
    groups: "abcxyz-new"
  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        state: present
        password: "{{ password }}"
        groups: "{{ groups }}"
        append: yes
    - name: Create group
      group:
        name: "{{ groups }}"
        state: present
