name: php-3-tier
version: '3'
services:
    frontend:
        image: httpd:latest
        ports:
            - 3000:80
        volumes:
            - ./frontend:/user/local/apache2/htdocs
    backend:
        image: pasangrumba123/php-3-tier-me
        ports:
            - 5000:80
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: todo_app
            MYSQL_USER: todo_admin
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:    
            - ./db:/docker-entrypoint-initdb.d

            