name: php-3-tier
version: '3'
services:
  frontend:
    image: httpd:latest
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
  backend:
    image: prakash9295/php-3tier-be-prakash
    volumes:
      - ./api:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d


