name: php-3-tier
version: '3'
services:
  fronted:
    image: httpd:latest
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
  backend:
    image: dpaktamang/php-3-tier-be
    volumes:
      - ./backend:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  