name: Deploy php-3-tier
on:
 push:
   branches:
     - test
     - prakash/feature-cloudformation-updates
jobs:
 deploy-php-app-cloudformation-stack:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         ref: prakash/feature-cloudformation-updates
     - name: install aws cli
       uses: unfor19/install-aws-cli-action@v1
       with:
         version: 2 
         verbose: false
         arch: amd64
     - name: check aws cli version
       run: aws --version
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ vars.AWS_DEFAULT_REGION }}

     - name: create s3 bucket
       run: aws s3 mb s3://my-cloudformation-templates-devops430 --region us-east-1
     - name: copy templates
       run: |
         aws s3 cp cloudformation-template/ s3://my-cloudformation-templates-devops430/ --recursive
         aws s3 cp scripts/user-data.sh s3://my-cloudformation-templates-devops430/
     - name: deploy stack
       run: |
         aws cloudformation create-stack \aws cloudformation create-stack \
           --stack-name php-3-tier \
           --template-url https://my-cloudformation-templates-devops430-a.s3.amazonaws.com/php-3-tier.yaml \
           --region us-east-1 \
           --parameters \
                 ParameterKey=KeyPairName,ParameterValue=my-key-pair \
                 ParameterKey=S3BucketName,ParameterValue=my-cloudformation-templates-devops430-a \
                 ParameterKey=UserDataFileName,ParameterValue=user-data.sh \
                 ParameterKey=EnableFrontendStorageStack,ParameterValue=false \
                 ParameterKey=EnableDatabaseStack,ParameterValue=false \
           --capabilities CAPABILITY_IAM
                      
 deploy-app:
   runs-on: ubuntu-latest
   needs: deploy-php-app-cloudformation-stack
   steps:
     - uses: actions/checkout@v4
       with:
         ref: prakash/feature-cloudformation-updates 
     - name: deploy frontend
       run: echo "Deploying frontend..."
     - name: deploy backend
       run: echo "Deploying backend..."
     - name: echo "Deploying database..."
       run: echo "Deploy database...."

